# Generated by Django 4.1.13 on 2023-12-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://www.wallpaperup.com/uploads/wallpapers/2014/09/26/457781/b3cb545383e59aef8287ba9422002866.jpg', max_length=500),
        ),
    ]
